# theme.toml template for a Hugo theme
# See https://nikola.ltd/ for an example

name = "Clean White"
license = "Apache"
licenselink = "https://nikola.ltd/"
description = "A clean, elegant blog theme for hugo"
homepage = "https://nikola.ltd/"
tags = [ "minimal", "responsive", "blog","light", "clean", "search"]
features = ["disqus", "site search", "responsive", "google analytics", "side bar"]
min_version = 0.10

[author]
  name = "Ambrose"
  homepage = "https://nikola.ltd/"

# If porting an existing theme
[original]
  name = "ambroseblog"
  homepage = "https://nikola.ltd/"
